# .github/workflows/cantina-build_main.yml
name: Cantina build - main branch
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
            java-version: 15
      - name: Unit and integration test with Maven
        run: mvn test verify -Dartifact_version=main
